
% MATLAB Code from Sensor Array Analyzer App

% Generated by MATLAB 9.12 and Phased Array System Toolbox 4.7

% Generated on 21-Sep-2023 11:51:44

% Create a uniform rectangular array
Array = phased.URA('Size',[64 64],...
    'Lattice','Rectangular','ArrayNormal','x');
Array.ElementSpacing = [0.007 0.007];
% Calculate Row taper
sll = 31;
rwind = chebwin(64, sll);
% Calculate Column taper
sll = 30;
cwind = chebwin(64, sll);
% Calculate taper
taper = rwind*cwind.';
Array.Taper = taper.';

% Create a cosine antenna element
Elem = phased.CosineAntennaElement;
Elem.CosinePower = [1 1];
Elem.FrequencyRange = [0 3500000000];
Array.Element = Elem;
% Assign Frequencies and Propagation Speed
Frequency = 3500000000;
PropagationSpeed = 300000000;


% Create Figure

% Plot Array Geometry
figure;
viewArray(Array,'ShowNormal',false,...
    'ShowTaper',false,'ShowIndex','None',...
    'ShowLocalCoordinates',true,'ShowAnnotation',false,...
    'Orientation',[0;0;0]);

% Calculate Steering Weights

Freq3D = 3500000000;
% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 3d graph
format = 'polar';
plotType = 'Directivity';
figure;
pattern(Array, Freq3D , 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format,'weights', w(:,1),...
    'ShowArray',false,'ShowLocalCoordinates',true,...
    'ShowColorbar',true,'Orientation',[0;0;0],...
    'Type', plotType);

% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 2d azimuth graph
format = 'polar';
cutAngle = 0;
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, -180:180, cutAngle, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format ,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);

% Find the weights
w = ones(getNumElements(Array), length(Frequency));

% Plot 2d elevation graph
format = 'polar';
cutAngle = 0;
plotType = 'Directivity';
plotStyle = 'Overlay';
figure;
pattern(Array, Frequency, cutAngle, -90:90, 'PropagationSpeed', PropagationSpeed,...
    'CoordinateSystem', format ,'weights', w, ...
    'Type', plotType, 'PlotStyle', plotStyle);

