%transmisor
viewer = siteviewer("Buildings","EstadioSiles.osm","Basemap","topographic");
tx = txsite("Name","Small cell transmitter", ...
 "Latitude",-16.50060, ...
 "Longitude",-68.12302, ...
 "AntennaHeight",10, ...
 "TransmitterPower",2, ...
 "TransmitterFrequency",3.5e9);
show(tx)
rx = rxsite("Name","Small cell receiver", ...
 "Latitude",-16.500163, ...
 "Longitude",-68.122608, ...
 "AntennaHeight",1);
pm = propagationModel("raytracing", ...
 "MaxNumReflections",5, ...
 "AngularSeparation","low", ...
 "BuildingsMaterial","perfect-reflector", ...
 "TerrainMaterial","perfect-reflector");
pm.BuildingsMaterial = "concrete";
pm.TerrainMaterial = "vegetation";

pm = pm + propagationModel("rain") + propagationModel("gas");

raytrace(tx,rx,pm,"Type","pathloss")
raysAtmospheric = raytrace(tx,rx,pm,"Type","pathloss");
plAtmospheric = [raysAtmospheric{1}.PathLoss] + " dB"
% raytrace(tx,rx,pm,"Type","pathloss")
% raysPerfect = raytrace(tx,rx,pm,"Type","pathloss");
% plPerfect = [raysPerfect{1}.PathLoss]
